workspace:
  base: /go
  path: src/github.com/EVE-Tools/market-stats

pipeline:
  build:
    image: golang:alpine
    commands:
      - apk update
      - apk add git
      - go get ./...
      - go build

  docker:
    image: plugins/docker
    repo: evetools/market-stats
    tag:
      - latest
      - ${DRONE_BRANCH}