package dogma

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDogmaEffectsReader is a Reader for the GetDogmaEffects structure.
type GetDogmaEffectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDogmaEffectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDogmaEffectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetDogmaEffectsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDogmaEffectsOK creates a GetDogmaEffectsOK with default headers values
func NewGetDogmaEffectsOK() *GetDogmaEffectsOK {
	return &GetDogmaEffectsOK{}
}

/*GetDogmaEffectsOK handles this case with default header values.

A list of dogma effect ids
*/
type GetDogmaEffectsOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []int32
}

func (o *GetDogmaEffectsOK) Error() string {
	return fmt.Sprintf("[GET /dogma/effects/][%d] getDogmaEffectsOK  %+v", 200, o.Payload)
}

func (o *GetDogmaEffectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDogmaEffectsInternalServerError creates a GetDogmaEffectsInternalServerError with default headers values
func NewGetDogmaEffectsInternalServerError() *GetDogmaEffectsInternalServerError {
	return &GetDogmaEffectsInternalServerError{}
}

/*GetDogmaEffectsInternalServerError handles this case with default header values.

Internal server error
*/
type GetDogmaEffectsInternalServerError struct {
	Payload GetDogmaEffectsInternalServerErrorBody
}

func (o *GetDogmaEffectsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dogma/effects/][%d] getDogmaEffectsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDogmaEffectsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetDogmaEffectsInternalServerErrorBody get_dogma_effects_internal_server_error
//
// Internal server error
swagger:model GetDogmaEffectsInternalServerErrorBody
*/
type GetDogmaEffectsInternalServerErrorBody struct {

	// get_dogma_effects_500_internal_server_error
	//
	// Internal server error message
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this get dogma effects internal server error body
func (o *GetDogmaEffectsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDogmaEffectsInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getDogmaEffectsInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}
